on: 
    push:
      branches:
        - ts_practise_1802024
jobs:
    pull-request:
        runs-on: ubuntu-latest
        steps:
          - name: Open PR
            id: open_pr
            uses: rematocorp/open-pull-request-action@v1
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              from-branch: ts_practise_1802024
              to-branch: angular_revision_21022024_auto_merge
              repository-owner: Ashraf840
              repository: Angular-101
          - name: Echo mergeable PR number
            run: echo ${{ steps.open_pr.outputs.pull_number }}
          - name: Get Commit Message
            run: |
              echo "Commit message: ${{ github.event.head_commit.message }}"
              echo "::set-output name=message::${{ github.event.head_commit.message }}"
    merge-branch:
      runs-on: ubuntu-latest
      steps:
        - name: Action Checkout
          uses: actions/checkout@v2
        - name: Get PR Commit Message
          run: |
            echo "Commit message was: ${{ needs.pull-request.outputs.commit.message }}"
        - name: Branch Merge Automation
          uses: everlytic/branch-merge@1.1.2
          with:
            github_token: ${{ github.token }}
            source_ref: ts_practise_1802024
            target_branch: angular_revision_21022024_auto_merge
            commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'