on: 
    push:
      branches:
        - ts_practise_1802024
jobs:
    pull-request:
        runs-on: ubuntu-latest
        steps:
          - name: Open PR
            id: open_pr
            uses: rematocorp/open-pull-request-action@v1
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              from-branch: ts_practise_1802024
              to-branch: angular_revision_21022024_auto_merge
              repository-owner: Ashraf840
              repository: Angular-101
              max-attempts: 30
          - name: Echo mergeable PR number
            run: echo ${{ steps.open_pr.outputs.pull_number }}
          - name: Check PR status
            uses: rematocorp/wait-for-check-action@v1  
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              check-name: pull_request # Status context name
              max-attempts: 30  # Increased this as well
    merge-branch:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: everlytic/branch-merge@1.1.2
          with:
            github_token: ${{ github.token }}
            source_ref: ts_practise_1802024
            target_branch: angular_revision_21022024_auto_merge
            commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

    # merge:  
    #     needs: pull-request
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Merge pull request
    #           uses: sudo-bot/action-pull-request-merge@v1.1.1
    #           with: 
    #             github-token: ${{ secrets.GITHUB_TOKEN }}


