on: 
  push:
    branches:
      - ts_practise_1802024
jobs:
  pull-request:
    uses: repo-sync/pull-request@v2
    with:
      destination_branch: "angular_revision_21022024_auto_merge"
      github_token: ${{ secrets.GITHUB_TOKEN }}

  merge:  
    needs: pull-request
    runs-on: ubuntu-latest
    steps:
    - name: Merge pull request
      uses: sudo-bot/action-pull-request-merge@v1.1.1
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
