on: 
  push:
    branches:
      - ts_practise_1802024
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Open PR
        id: open_pr
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          from-branch: change_this
          to-branch: change_this
          repository-owner: change_this
          repository: change_this
          
      - name: Echo mergeable PR number
        run: echo ${{ steps.open_pr.outputs.pull_number }}

  merge:  
    needs: pull-request
    runs-on: ubuntu-latest
    steps:
    - name: Merge pull request
      uses: sudo-bot/action-pull-request-merge@v1.1.1
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
